### ISSUE TITLE
setState calls on unmounted component

### ISSUE THREAD

**Issue by grigory-leonenko** [axept/react-remote-image#1]
If Image not loaded yet but component unmounted, onload method calls setState and React throw warning.

**Comment by DenisIzmaylov** [comment]
Thank you for feedback. Yes, it's general issues for dynamic UI in React. It seems we have to add something like:

``` javascript
componentWillUnmount() {
  this._unmounted = true
}

// when image is ready
  if (this._unmounted !== true) {
    this.props.onLoad(...);
  } 
```

**Comment by grigory-leonenko** [comment]
Fixed with add and remove event listeners for image.
